only signed updates via updateOS

diff --git a/updateOS b/updateOS
--- a/updateOS
+++ b/updateOS
@@ -55,6 +55,9 @@ VERSION="$(curl --silent https://api.github.com/repos/codecivil/$REPO/releases/l
 # make new dir if new version is available
 mkdir "$WEBDIR/$VERSION" 2>/dev/null && {
 	curl --silent "https://api.github.com/repos/codecivil/$REPO/releases/latest" | grep 'tarball_url' | sed 's/.*\": //;s/,//' | xargs wget -O openStat.tgz
+	#get and verify signature
+	curl --silent "https://www2.codecivil.de/signatures/$REPO/$REPO-$VERSION.sig"
+	gpg verify "$REPO-$VERSION.sig" openStat.tgz || { echo "Update cannot be verified."; exit 1; }
 	# extract and install...
 	mv openStat.tgz "$WEBDIR/$VERSION"
 	cd "$WEBDIR/$VERSION"
@@ -96,6 +99,10 @@ cp -a "$WEBDIR/$OLDVERSION/$INSTANCE.tgz" "$WEBDIR/latest/"
 VERSION="$(curl --silent https://api.github.com/repos/codecivil/$REPO/releases/latest | grep 'tag_name' | sed 's/.*\": //;s/,//;s/\"//g' )"
 if [[ "$VERSION" != "$OLDVERSION" ]]; then
 	curl --silent "https://api.github.com/repos/codecivil/$REPO/releases/latest" | grep 'tarball_url' | sed 's/.*\": //;s/,//' | xargs wget -O $INSTANCE.tgz
+	#get and verify signature
+	curl --silent "https://www2.codecivil.de/signatures/$REPO/$REPO-$VERSION.sig"
+	gpg verify "$REPO-$VERSION.sig" openStat.tgz || { echo "Update for $REPO cannot be verified."; exit 1; }
+	##
 	mv $INSTANCE.tgz "$WEBDIR/latest/"
 fi
 # make new dir if new version is available
